api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Doctrine/Mapping/Entity'
            - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'Symfony-Playground'
    description: 'lorem ipsum'
    version: 1.0
    show_webby: false