App\Entity\Product:
  type: entity
  table: products

  id:
    id:
      type: string

  manyToMany:
    companies:
      targetEntity: Company
      inversedBy: products
      joinTable:
        name: company_products
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          company_id:
            referencedColumnName: id

  fields:
    name:
      type: string
      nullable: false
    price:
      type: int
      nullable: false
    createdAt:
      type: datetime
      nullable: false
    updatedAt:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    preUpdate: [markAsUpdated]
