apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: symfony-playground-be
  name: symfony-playground-be
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: symfony-playground-be
    spec:
      containers:
        - env:
            - name: PHP_EXTENSION_XDEBUG
              value: "1"
          image: be:v1
          name: symfony-playground-be
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
