apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: symfony-playground-be
  name: symfony-playground-be
spec:
  ports:
  - name: "9002"
    port: 9002
    targetPort: 9000
  selector:
    io.kompose.service: symfony-playground-be
status:
  loadBalancer: {}
