apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: symfony-playground-db
  name: symfony-playground-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: symfony-playground-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: symfony_playground
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: symfony-playground-db
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
