version: '2.1'
services:
    symfony-playground-db:
        container_name: symfony-playground-db
        restart: always
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5433:5432'
    symfony-playground-be:
        container_name: symfony-playground-be
        build: 
            context: php-fpm
            args:
                UID: $U_ID
        ports:
            - '9002:9000'
        volumes:
            - .././:/appdata/www
            - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
        depends_on:
            - symfony-playground-db
    symfony-playground-web:
        build: nginx
        container_name: symfony-playground-web
        ports:
            - '8080:80'
        volumes_from:
            - symfony-playground-be
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - symfony-playground-be