version: '2.1'
services:
    postgres:
        restart: always
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5433:5432'
    php:
        container_name: symfony-playground-be
        build: 
            context: php-fpm
            args:
                UID: $U_ID
        ports:
            - '9002:9000'
        volumes:
            - .././:/appdata/www
            - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
        links:
            - postgres
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached